### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by NetConsulting** [amwhalen/archive-my-tweets#33]
Hi there!
I loved the idea to archive tweets, but it seems to have stopped working.
On the example at http://amwhalen.com/twitter/ the last tweet is from 10:15am March 9th 2014 and after that date no tweets have been added.
Can you confirm that it isn't working any more?
Is there any workaround to make it work again?

Thanks.

**Comment by ProgVal** [comment]
It's just that the author stopped tweeting… see https://twitter.com/awhalen/with_replies

It works for me: http://amt.progval.net/

**Comment by NetConsulting** [comment]
Thanks for the info. I just managed to make it work.

The issue was that I filled in the data in config.php and didn't run the installation; but you need to run the installation so that it Works and that you don't receive an "max id is null " error.
