### ISSUE TITLE
Error logs related to date()

### ISSUE THREAD

**Issue by topher1kenobe** [amwhalen/archive-my-tweets#34]
On every page load I get this:

[Fri May 15 10:30:20 2015] [warn] mod_fcgid: stderr: PHP Warning:  date() [<a href='function.date'>function.date</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/Los_Angeles' for 'PDT/-7.0/DST' instead in /home/cv/domains/twitter.codeventure.net/public_html/themes/default/index.php on line 63

[Fri May 15 10:30:20 2015] [warn] mod_fcgid: stderr: PHP Warning:  date() [<a href='function.date'>function.date</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/Los_Angeles' for 'PDT/-7.0/DST' instead in /home/cv/domains/twitter.codeventure.net/public_html/themes/default/index.php on line 64

several hundred times in my error logs.  It's making my log file grow VERY quickly.

**Comment by topher1kenobe** [comment]
A quick fix was simply to put this in config.php:
date_default_timezone_set('America/New_York');

**Comment by amwhalen** [comment]
You're correct. The call to date_default_timezone_set() is already in config.example.php but left blank to setup during installation.
