### ISSUE TITLE
Project dead ?

### ISSUE THREAD

**Issue by Draky50110** [amwhalen/archive-my-tweets#43]
Hello @amwhalen is your project dead ?
Your personal webpage seems to be blank.

Yor project still works for me but... httpS is not well supported...

**Comment by progval** [comment]
> httpS is not well supported...

What do you mean? I'm running archive-my-tweets on master and don't have any issue with https

**Comment by Draky50110** [comment]
https://gilles.wittezaele.fr/tweets/ with no good style...

Found the problem : img/avatar.png is not laoded with httpS so browsers are blocking because of unsecure content...
Don't know how to change http into httpS loading.

Anywya, question is the same : is project still active ?

**Comment by chtitux** [comment]
>Don't know how to change http into httpS loading.

Set `baseUrl` with `https://`  instead of `http://`

> is project still active ?

Probably a bit :ghost: :)

**Comment by Draky50110** [comment]
OMG it works :)
In config.php :)

Thanks @chtitux
